server {
    listen 80;
    root /var/www-site;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_log  /var/log/nginx/site-error.log;
    access_log /var/log/nginx/site-access.log;
}
